### PR TITLE
fixes after eucalyptus upgrade

### PR DESCRIPTION
**Pull request by ziafazal**
These changes achieve these goals.
- Upgrade to Eucalytus name release that means upgrading to Django 1.8 and DRF 3.2
- Fix broken tests and optimize/clean them where possible

@msaqib52  would you please review?

### CODE REVIEW

**Comment by msaqib52** [comment]
LGTM 👍

**Comment by ziafazal** [comment]
@douglashall would you be able to review this one?

**Comment by douglashall** [comment]
@ziafazal Sure thing. Would it be possible for you to summarize the changes that needed to be made for Django 1.8 and DRF 3.2 upgrades?

**Comment by ziafazal** [comment]
@douglashall Thanks. Changes in this PR are related to these modifications in Django 1.8 and DRF 3.2 upgrades.

**Django 1.8**

- No more South based migrations.
- Introduction of AppConfig for app related configurations
- Enhancement modifications to transactions. Some methods deprecated.
- 

**DRF 3.2**

- Removed request.QUERY_PARAMS in favour of request.query_params
- Removed request.DATA in favour of request.data

**Pull request merged**
