### PR TITLE
[MCKIN-6668] Fix Bugs Introduced from PR #1020

### PR DESCRIPTION
**Pull request by macornwell**
This pull request fixes two bugs that were introduced from [PR #1020.](https://github.com/edx-solutions/api-integration/pull/119).
The two bugs were:

1. Unit test failures due to lack of authentication.
2. Division with error.

**JIRA tickets**: MCKIN-6668

**Merge deadline**: "None"

**Reviewers**
- [ ] @jcdyer 
- [ ] @mtyaka

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @macornwell! I've created [OSPR-2233](https://openedx.atlassian.net/browse/OSPR-2233) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx-solutions/api-integration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by aamishbaloch** [comment]
@macornwell @bradenmacdonald Please see @ziafazal's comment on [MCKIN-6668](https://edx-wiki.atlassian.net/browse/MCKIN-6668). Maybe we don't need this change anymore.

**Comment by macornwell** [comment]
@aamishbaloch  Ok good to go. I don't have access to the link so I'll take your word for it.

**Comment by bradenmacdonald** [comment]
Closing in favor of @ziafazal 's solution.

**Pull request closed without merging**
