### PR TITLE
added new company admin creation script

### PR DESCRIPTION
**Pull request by kotky**
@ziafazal @fredsmith  This is a new pull request for company admin role

### CODE REVIEW

**Comment by msaqib52** [comment]
@kotky please add tests to support your changes.

**Comment by fredsmith** [comment]
why not use get_or_create?  https://docs.djangoproject.com/ja/1.9/ref/models/querysets/#get-or-create

**Comment by ziafazal** [comment]
@kotky once we merged this PR. you need to create a release on this repo bumping the version and then update the version of api-integration app in `edx-platform/requirements/edx/custom.txt` to reflect these changes in edx-platform.

**Comment by kotky** [comment]
added tests

**Pull request merged**
